Add availability indicator to mentor page
ZTL-ARTCC/scheddy pull request #14
Opened 2024-12-01 02:35 UTC by Evanston09

This PR will:
- Allow staff to view if mentors have availability at a glance.
- Close #13

2024-12-02 17:38 UTC, c0repwn3r requested changes

2024-12-02 17:38 UTC, c0repwn3r commented on src/routes/(authed)/dash/mentors/+page.server.ts
> +		const mentorAvailability = JSON.parse(mentor.mentorAvailability!);
This will return 500 on mentors that do not have availability set (which IS possible)

2024-12-02 17:44 UTC, Evanston09 commented on src/routes/(authed)/dash/mentors/+page.server.ts
> +				.some((day) => mentorAvailability[day].available === true);
I think if you set availability then later get rid of it the db will show all the days of the week just the available key is set to false. So just setting it based on null won't always work

2024-12-03 00:53 UTC, Evanston09 commented on src/routes/(authed)/dash/mentors/+page.server.ts
> +		const mentorAvailability = JSON.parse(mentor.mentorAvailability!);
Can you elaborate? I do not get a 500 even if the `mentorAvailability` field is null.

2024-12-03 14:58 UTC, c0repwn3r commented on src/routes/(authed)/dash/mentors/+page.server.ts
> +				.some((day) => mentorAvailability[day].available === true);
Got it. In that case, please update the description at the top of the page - maybe "Green light indicates mentor is available at least one day"

2024-12-03 14:58 UTC, c0repwn3r commented on src/routes/(authed)/dash/mentors/+page.server.ts
> +		const mentorAvailability = JSON.parse(mentor.mentorAvailability!);
Ah, I didn't see this was in a .map(). Works ok

2024-12-03 15:01 UTC, c0repwn3r commented on src/routes/(authed)/dash/mentors/+page.svelte
> +	Mentors and instructors are added automatically by their VATUSA role. Mentors with availability
```diff
- Mentors with availability
+ Mentors available on at least one day
```
Maybe something like this, so it's more clear what the green dot indicates.

2024-12-05 16:02 UTC, c0repwn3r approved these changes
Good work! Bump the patch version to 1.1.1 then merge.

2024-12-05 22:53 UTC, merged